### ISSUE TITLE
Reflexion

### ISSUE THREAD

**Issue by Louis9902** [Louis9902/Sosse19-SE#11]
Vergleichen Sie die frühe Planung in den ersten Wochen mit den dem Ergebnis am Ende.
> Entspricht das Ergebnis Ihrer ursprünglichen Vision?

Das Ergebniss unseres Projektes entspricht zu Teilen der Idee des Uhsprunglichen Projektes. Jedoch gab es imlaufe der Entwicklung einige Auffälligkeiten welche zu einer neu Orientierung der eigentlichen Ziele geführt haben. 

> Was lief wie geplant, welche (überraschenden?) Änderungen haben sich ergeben?

So ist die Uhrsprungliche Idee eines Backup Programmes relative schnell verworfen worden, da dies einen zu geringen nutzen gegenüber des Enticklunhsaufwandes hätte. Anstatt dessen ist ein Framework artiges Projekt entschanden welches bilib mit weiteren Aufgaben Typen erweitert werden kann. 

> An welcher Stelle sind Sie nicht weitergekommen, wo haben Sie am meisten dazugelernt?
> Hat sich die geplante Arbeitsaufteilung bewährt?
> Was würden Sie für das nächste Projekt anders machen?

Dabei ist es uns aufgefallen das man bereits vor dem eigentlichen Projekt start den Terminus von bestimmten wörtern besser klären sollte um miss verständnisse zu vermeiden. Dazu kommt das für die anschließende Implementierung in der Zukunft eine bessere Aufteilung erfolgen sollte, dies bezieht sich dabei auf einen genuer spezifikation wer was Implemenieren soll und an was für einen Standart sich gehalten werden soll. Dabei ist es eigentlich unabgänglich ein Versionirungs system wie git zu benutzen. Aufgrund vom mängelnden Git käntnissen in der Projekt Gruppe hat sich dies jedoch nicht als möglich erwiesen. (Pull Request etc. um dem Projekt Manager die möglichkeit zu geben anderungs vorschläge anzu bringen bevor dies bestandteil des Programmes wird.)

**Comment by Louis9902** [comment]
Vergleichen Sie die frühe Planung in den ersten Wochen mit den dem Ergebnis am Ende.
-	Entspricht das Ergebnis Ihrer ursprünglichen Vision?
-	Was lief wie geplant, welche (überraschenden?) Änderungen haben sich ergeben?
-	An welcher Stelle sind Sie nicht weitergekommen, wo haben Sie am meisten dazugelernt?
-	Hat sich die geplante Arbeitsaufteilung bewährt?
-	Was würden Sie für das nächste Projekt anders machen?

**Comment by JensWoe** [comment]
Also dass wir ein Framework und kein Backup-Programm schreiben wollten hör ich ehrlich gesagt gerade zum ersten Mal. Wir haben doch erst gedacht, dass wir 2 Arten von Workern brauchen. Also hast du das als abstrakte Klasse erstmal implementiert. Aber dann haben wir halt doch nicht 2 gebraucht.

**Comment by Louis9902** [comment]
Naja das ding ist ja wenn du etwas bis zu einenm bestimmten punkt abstrahirst dann ist es ja quasi belibig erweiterbar und as ist damit als "Framework" gemeint.

**Comment by JensWoe** [comment]
Ok ich wollte mich gerade beschweren, dass das dann gar nicht zu der Kurzbeschreibung passt die ich mal übersetzt hab, aber die wurde ja schon ersetzt und dazu angepasst. Hauptsache es ist stimmig, dass man oben dem "Kunden" kein Backup-Programm verkauft und unten steht dann irgendwas von abstraktem Framework.

**Comment by Louis9902** [comment]
Jap das ist aber schon etwas länger ausgetauscht...
