### ISSUE TITLE
Projektabschluss

### ISSUE THREAD

**Issue by Louis9902** [Louis9902/Sosse19-SE#14]
1. Pitch: Was ist es, das Sie gebaut haben?
z.B. Unser <Projekt X> ist ein/e {Service, App, …} um Y zu machen. Anders als 
Konkurrenz K, konzentriert sich X auf …
2. Erläutern Sie die wichtigste Anforderung
3. Erläutern Sie die ein/en Use Case, Klassen- oder Sequenzdiagramm
4. Link zum Demovideo (30-60s), ohne Ton (Text dann live und in Farbe…)
5. Was lief gut, was lief schlecht? z.B. Requirements, Teamwork, …

Wer möchte den Vortrag machen? Ich habe ehrlich gesagt eigentlich kein Interesse daran 😅
@JensWoe @Luke2706 @mo-wein

**Comment by Louis9902** [comment]
1. Unser Projekt ist ein Framework zum AUtomatisiren von kleinerene Aufgaben, diese Aufgaben können vom Benutzer selbst erstellt werden und werden dann von unserer Applikation organisiert. Unser Framework unterscheidet sich von anderen sin so fern das es zum einen komplett quell offen ist und auch nach beliben erweitert werden kann um jeden Use Case den sich ein benutzer denken kann abzudecken. Unsere Appliktion beschränkt sich dabei auf das Organisiren und verwalten der Aufgaben.

2. Die wichtigsten Anforderungen an user Framework sind die Zuverlässigkeit sowie die Benutzerfreundlichkeit. Mit Benutzerfreundlichkeit ist gemeint das es dem Benutzer ermöglicht wird sämtliche Einstellungen des Programmes über eine Benutzeroberfläche vorzunehmen.

3. Sequenzdiagramm: Das laden der Configuration und das starten der Aufgaben.

4. Das Video vom offen des UI sowie das erstellen des Workers mit anschleßemden Schlißen der Application.

5. _To be Done_

**Comment by JensWoe** [comment]
Zu 1. Ich hab noch ein paar Ideen von dir oben übernommen. Müsste jetzt alles auf der Folie sein. In den Kommentaren hab ich alles bisschen mehr ausformuliert, dass man das fast schon "ablesen" kann.
Zu 2. Man soll ja glaube nur eine Anforderung ansprechen. Ich hab mich jetzt für die Benutzerfreundlichkeit entschieden. 
Zu 3. Diagramm ist schon eingefügt. In den Kommentaren ist es erklärt. 
Zu 4. Ja da ist nichts : D
Zu 5. Ja ist eigentlich schon fertig. Da haben wir in der Uni ja 3 negative und 2 positive gefunden. Wenn noch jemandem was einfällt was gut gelaufen ist in dem Projekt immer her damit : D
Edit: Ok hab das Sequenzdiagramm noch animiert. Siehe Video

**Comment by Louis9902** [comment]
Also da ist das Video: https://youtu.be/W7AzKfIcEZU willst du es einbetten?

**Comment by Louis9902** [comment]
Hier sind ein paar Änderungen: 6758aa316d405aaeaa4891c5f09778832ae891af

**Comment by JensWoe** [comment]
@sikoried Wir fragen uns gerade wie streng die Auflage mit den 5 Folien in der PowerPoint Präsentation ist. Den ich habe das Sequenzdiagramm animiert, wobei ich einfachheitshalber für jeden Animationsschritt eine neue Folie erstellt habe. Genauso für das Video, was ich auf einer zusätzlichen Folie Vollbild eingebettet habe.
Somit komm ich bereits auf 16 Seiten, wobei inhaltlich nur die 5 Punkte bearbeitet werden.
Hier ist der Link zu der PP-Präsentation: https://github.com/Louis9902/Sosse19-SE/blob/master/Praktikumsbericht/Abschlusspraesentation.pptx

**Comment by sikoried** [comment]
Hallo,
5 Seiten sind 5 Seiten, incl. dem Link/Embedding des Videos. Für das Sequenzdiagramm: Nehmen Sie einfach die Animation raus, dann ist es eine Folie.
Gruss,
KR
