### ISSUE TITLE
Zustandsdiagramme

### ISSUE THREAD

**Issue by Louis9902** [Louis9902/Sosse19-SE#4]

**Comment by Louis9902** [comment]
Dafür würde ich den gesamt vorgang von staretne und stoppen des Serives nehmen also siehe dafür #3 und berücksichtige dabei das das ganze noch einmal in die gegengesetzte richtung geht.
https://github.com/Louis9902/Sosse19-SE/blob/486188df434997b05654f4584937d09786061372/Implementierung/TinyTasksService/Program.cs#L43-L47

**Comment by Luke2706** [comment]
[Zustandsdiagram](https://github.com/Louis9902/Sosse19-SE/blob/master/Diagramme/Zustand/TinyTasks.svg)
@sikoried Passt das Zustandsdiagramm so?

**Comment by sikoried** [comment]
Sieht gut aus!
