### ISSUE TITLE
Implementirungsbeschreibung

### ISSUE THREAD

**Issue by Louis9902** [Louis9902/Sosse19-SE#8]
Für die Implementierung des Projektes haben wir uns für das .NET Framework entschieden da dieses
auf unterscheidlichen Betriebssystemen läuft, daruch gibt es eine grösere flexibilität ber der Anwendung.
Toolkits wurden für diese Projekte keine externen hinzugezoden lediglich die Standart libraries von .NET.

Erfüllte Anforderungen:
 - Anforderung 1: wurde voll und ganz erfüllt (siehe Benutzeröberflächen beispiele)
 - Anforderung 2: wurde ebenfalls erfüllt, wenn auch die aktuelle implementierung lediglich nur einen Typ von Aufgabe zu lässt. Dies ist aber einfach zu erweitern da das gesamte system relative allgemein gehalten ist.
 - Anforderung 3: diese ist für manche Datentypen erfüllt, wobei das System zum überprüfen ebenfalls wieder sehr offen gehalten ist, was eine einfache erweiterung zu einem späteren Zeitpunk zu lässt.
 - Anforderung 5: wurde im vollen umfang implementiert und ist weitesgehend unabhängig von der laufzeitplatform platform

Nicht erfüllte Anforderungen:
 - Anforderung 4: diese ist prinzipell möglich, jedoch nicht aktiv implementiert. Die nötigen strukturen bestehen jedoch und die implementierung kann erfolgen wenn diese benötigt werden sollte.

 Beiträge der Teilnehmer:
  - Jens:
    + Erste Implementierung der Benutzeröberfläche
    + Implementierungserweiterungen der Benutzeröberfläche
    + Ideenfindung für User Stories, Use Case (Diagramm/Tabelle), Classes

  - Lukas:
    + Erste Version des Class Diagramm
    + Erstellen des Sequenzdiagramm
    + Erstellen des Statediagramm
    + Ideenfindung für User Stories, Use Case, Classes

  - Louis (over complicated stuff gerne ;S):
    + Projekt Managment
    + Implementierung der Programmierschnittstelle und des Hintergrundprozesses
    + Überarbeitung der ersten Version der Benutzeröberfläche (1)
    + Erstellen des Class Diagramm (Überarbeitung und Spezifizirung)
    + Erstellen einer Überarbeiteten Version des Use Case Diagramm + Tabelle
    + Erstellen und Zusammentragen dieses Dokumentes

  - Moritz:
    + nichts :P
    + eigentlich: Objekt Diagramm

(1) Aufgrund eines Missverständnisses bezüglich des Modularen Aufbaus für eine spätere erweiterung.

**Comment by Louis9902** [comment]
@JensWoe @Luke2706 
Habe ich was vergessen soll ich was anders schreiben wenn ja bitte ein kommentar schreiben, das werde ich das abändern.

**Comment by JensWoe** [comment]
Du hast ungefähr überall Benutzeröberflächen statt Benutzeroberfläche geschrieben :D

**Comment by JensWoe** [comment]
Und ich würde alles was einen Smiley im Satz hat weglassen, aber des sind wahrscheinlich eh alles Stellen wo noch was kommt?

**Comment by Louis9902** [comment]
Das sind alles nur so Ideen gewesen... 😅
