### ISSUE TITLE
User Stories and Use Cases

### ISSUE THREAD

**Issue by Louis9902** [Louis9902/Sosse19-SE#9]

**Comment by Louis9902** [comment]
@JensWoe Ich habe schon ein paar Ideen rein geschrieben aber sieht noch sehr dürftig aus.

**Comment by JensWoe** [comment]
Meine Vorschläge, nur damit sie irgendwo gespeichert sind: 
Als Benutzer möchte ich die aktuelle Konfiguration einsehen können, sodass sie mithilfe einer graphischen Benutzeroberfläche angezeigt wird.
Als Benutzer möchte ich einen neuen Task hinzufügen können, sodass diese Dateien auch gesichert werden.
Als Benutzer möchte ich einen existierenden Task entfernen können, sodass diese Dateien nicht mehr gesichert werden.
Als Benutzer möchte ich das Programm beenden können oder den Computer herunterfahren können ohne dabei die internen Daten des Programmes zu beschädigen.

**Comment by JensWoe** [comment]
Ups den Letzten hab ich nur halb kopiert:
Als Benutzer möchte ich das Programm beenden können oder den Computer herunterfahren können ohne dabei die internen Daten des Programmes zu beschädigen.

**Comment by Louis9902** [comment]
@JensWoe Ich würde sagen wir fragen einfach mal 😅
@sikoried Wie würde das aussehen wenn wird das System mit in die User Stories mit einbauen, oder soll das eher nicht der fall sein? 
Als referenz unser Anwendungsfalldiagramm [Anwendungsfalldiagramm](https://github.com/Louis9902/Sosse19-SE/blob/master/Diagramme/Anwendungsfall/TinyTasks.svg)

**Comment by sikoried** [comment]
Das (Betriebs-?) System sehe ich nicht als Akteur: Die Anforderung, dass das Herunterfahren keine Probleme verursacht ist, gehört nicht in die Use Cases -- sondern eben in die Requirements und dann in die Implementierung.

Was mir an Ihren UC noch auffaellt: Inwiefern ist "abort workers" eine Erweiterung von "start workers"? ...und inwieweit beinhaltet "abort" "save" sowie "start" "load"? Ebenso im rechten Teil (User Interface): wie kann "create worker" eine erweiterte Fassung von "open user interface" sein? 

Ist es nicht eher so, dass es nur eine Box "Worker Management" mit den UC start, stop, load, save ist (jeweils vom User erreichbar), und eine Box "GUI" dann nur "configure worker" enthält? "open user interface" und "exit user interface" sind ja nicht wirklich UC oder? "configure worker" könnte dann evtl. noch save/load inkludieren.

**Comment by Louis9902** [comment]
> Was mir an Ihren UC noch auffaellt: Inwiefern ist "abort workers" eine Erweiterung von "start workers"?

Nach meinem verständniss ist **abort workers** in sofern eine erweiterung von **start workers**, da dies ja nur erfolgen kann wenn bereits worker gestartet sind.

> ...und inwieweit beinhaltet "abort" "save" sowie "start" "load"?

Ebenso ist **save** in sofern in **abort** enthalten da wenn ich meine worker stoppe diese dann ihre daten speichern. bzw. in dem anschluss daran.
https://github.com/Louis9902/Sosse19-SE/blob/0e78c232415c30854dace152aed0850ee4e9bf79/Implementierung/TinyTasksService/Program.cs#L45-L46

Das ist ähnlich für **save** in **start**, da hier ja auch erst geldaen werden muss bevor ich etwas staretn kann.
https://github.com/Louis9902/Sosse19-SE/blob/0e78c232415c30854dace152aed0850ee4e9bf79/Implementierung/TinyTasksService/Program.cs#L39-L41

>Ebenso im rechten Teil (User Interface): wie kann "create worker" eine erweiterte Fassung von "open user interface" sein?

Das im User Interafce ist villeicht etwas umständlich formuliert aber es ist so gemeint: Der Benutzer kann ja nur dann einen neuen Worker erstellen wenn er das Interface geöffnet hat.
Was aber ja nicht zur "aktion" offnen gehört. Soll man dann einfach die Abhängigkeit weg lassen oder dir UC ganz raus nehmen?

**Comment by sikoried** [comment]
Ah jetzt kommen wir dem Missverständnis langsam auf den Grund: Save und Load sind gar keine UC, der User das nicht explizit (und isoliert) machen kann, sondern es sind Aktionen, welche innerhalb des UC Starten/Enden ausgeführt werden. Solche werden dann in der textuellen Beschreibung aufgenommen.

Ich sehe GUI öffnen/schließen nicht als UC, das ist ja nur Mittel zum Zweck. Der UC ist das Erstellen (bzw. Konfigurieren) des Workers (bevor er dann irgendwann gestartet wird).
